defaults:
  - default
  - _self_

models:
  world_model:
    model_name: "${exp_name}_world_model"
    description: "Offline Dreamer World Model used in ${env.id} Environment"
    tags: {}
  actor:
    model_name: "${exp_name}_actor"
    description: "Offline Dreamer Actor used in ${env.id} Environment"
    tags: {}
  critic:
    model_name: "${exp_name}_critic"
    description: "Offline Dreamer Critic used in ${env.id} Environment"
    tags: {}
  target_critic:
    model_name: "${exp_name}_target_critic"
    description: "Offline Dreamer Target Critic used in ${env.id} Environment"
    tags: {}
  moments:
    model_name: "${exp_name}_moments"
    description: "Offline Dreamer Moments used in ${env.id} Environment"
    tags: {}
