# @package _global_

defaults:
  - offline_dreamer_robosuite
  - override /algo: offline_dreamer_S
  - override /env: robosuite
#  - override /model_manager: p2e_dv3_finetuning
  - _self_

# Experiment
seed: 5

# # Environment
env:
  capture_video: True
  wrapper:
    bddl_file: null
  # num_envs: 4
#   action_repeat: 2
#   max_episode_steps: -1
#   wrapper:
#     domain_name: walker
#     task_name: walk
#     from_vectors: False
#     from_pixels: True

# Buffer
# buffer:
#   load_from_pretrain: False

checkpoint:
  pretrain_ckpt_path: ???
  every: 10000
  buffer:
    load_from_pretrain: False

# Algorithm
algo:
  offline: False
  total_steps: 10_000_000
  cnn_keys:
    encoder:
      - agentview_rgb
    decoder:
      - agentview_rgb
  mlp_keys:
    encoder: []
  learning_starts: 10_000
  replay_ratio: 0.5
  finetuning:
    freeze:
      encoder: True
      decoder: False
      actor: False
      critic: False
      world_model: False
      cbm_model: False


# Metric
metric:
  log_every: 1000

fabric:
  accelerator: cuda
  precision: bf16-mixed
  # precision: None
  # plugins:
  #   - _target_: lightning.fabric.plugins.precision.MixedPrecision
  #     precision: 16-mixed
  #     device: cuda
  #     scaler:
  #       _target_: torch.cuda.amp.GradScaler
  #       init_scale: 1e4
  #       growth_interval: 1000
